#!/usr/bin/env ruby
#
# Usage: bl master [-q]
# Summary: Checks out the master branch, prunes local branches
# Help: Example:
#
#    bl master
#

ROOT = File.expand_path(File.join(File.dirname(__FILE__), "..")).freeze

$:.push ROOT
require "lib/echo"
require "lib/git"
require "lib/validations"
require "shellwords"
require "optparse"



# Parse options

$quiet = false
OptionParser.new do |opts|
  opts.on("-q", "--quiet", "Quiet") do
    $quiet = true
  end
end.parse!



# Validation

assert_git_repo!


if Git.has_uncommitted_changes?
  echo_run! "git stash save -u -q", echo: !$quiet
end

unless Git.current_branch == "master"
  echo_run! "git checkout master > /dev/null 2>&1", echo: !$quiet
end

echo_run! "git pull origin master -q", echo: !$quiet

# List local branches whose heads have been merged to origin/master
branches_merged_to_master = `git branch --merged master --no-color`.split - %w{ * master }

unless branches_merged_to_master.empty?
  if branches_merged_to_master.length == 1
    announce "1 branch pruned"
    puts "   Restore it with:"
  else
    announce "#{branches_merged_to_master.length} branches pruned"
    puts "   Restore them with:"
  end

  branches_merged_to_master.each do |branch|
    sha = Git.show_ref(branch)
    system "git branch -D -q #{branch}"
    puts "      git branch #{Shellwords.escape(branch)} #{sha}"
  end

  puts ""
end

# List local branches
local_branches = `git branch --no-color`.split - %w{ * master }

if local_branches.empty?
  puts "   No local branches"
else
  puts "   Local branches:"
  local_branches.each do |branch|
    puts "      #{branch}"
  end
end

puts ""
